# Generated by Django 5.0.3 on 2024-03-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('abreviacio', models.CharField(max_length=3)),
                ('estadi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataGoal.estadi')),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('equip_a_favor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gol_a_favor', to='dataGoal.equip')),
                ('equip_en_contra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gol_en_contra', to='dataGoal.equip')),
            ],
        ),
        migrations.CreateModel(
            name='Partit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip_local', to='dataGoal.equip')),
                ('equip_visitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip_visitant', to='dataGoal.equip')),
                ('estadi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataGoal.estadi')),
                ('gols', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataGoal.gol')),
            ],
        ),
    ]
