# Generated by Django 5.0.3 on 2024-05-07 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataGoal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any', models.CharField(max_length=50)),
                ('titul', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='partit',
            name='equip_visitant',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='equip_local',
        ),
        migrations.RemoveField(
            model_name='gol',
            name='equip_a_favor',
        ),
        migrations.RemoveField(
            model_name='gol',
            name='equip_en_contra',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='estadi',
        ),
        migrations.RemoveField(
            model_name='partit',
            name='gols',
        ),
        migrations.CreateModel(
            name='EstadistiquesEquip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('abreviacio', models.CharField(max_length=3)),
                ('estadi', models.CharField(max_length=50)),
                ('escut', models.ImageField(upload_to='')),
                ('gols_favor_local', models.IntegerField(default=0)),
                ('gols_favor_visitant', models.IntegerField(default=0)),
                ('gols_en_contra_local', models.IntegerField(default=0)),
                ('gols_en_contra_visitant', models.IntegerField(default=0)),
                ('victorias_local', models.IntegerField(default=0)),
                ('victorias_visitant', models.IntegerField(default=0)),
                ('empates_local', models.IntegerField(default=0)),
                ('empates_visitant', models.IntegerField(default=0)),
                ('derrotas_local', models.IntegerField(default=0)),
                ('derrotas_visitant', models.IntegerField(default=0)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataGoal.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='Comparacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadistiquesEquip1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip1', to='dataGoal.estadistiquesequip')),
                ('estadistiquesEquip2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip2', to='dataGoal.estadistiquesequip')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataGoal.temporada')),
            ],
        ),
        migrations.DeleteModel(
            name='Equip',
        ),
        migrations.DeleteModel(
            name='Estadi',
        ),
        migrations.DeleteModel(
            name='Gol',
        ),
        migrations.DeleteModel(
            name='Partit',
        ),
    ]
