# Generated by Django 5.0.3 on 2024-05-08 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataGoal', '0002_temporada_remove_partit_equip_visitant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadistiquesequip',
            name='escut',
        ),
        migrations.AddField(
            model_name='comparacio',
            name='last_save_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estadistiquesequip',
            name='escut_url',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCugpPDzvVCn-fLGeKlz8A772i7SvZJ8OyJA&usqp=CAU'),
        ),
    ]
