# Generated by Django 5.0.2 on 2024-05-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataGoal', '0004_comparacio_user_estadistiquesequip_user_and_more'),
        ('dataGoal', '0007_estadistiquesequip_user_temporada_user_and_more'),
    ]

    operations = [
    ]
