# Generated by Django 5.0.2 on 2024-05-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataGoal', '0008_merge_20240509_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadistiquesequip',
            name='user',
        ),
        migrations.RemoveField(
            model_name='temporada',
            name='user',
        ),
    ]
