# Generated by Django 5.0.2 on 2024-05-13 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataGoal', '0009_remove_estadistiquesequip_user_remove_temporada_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comparacio',
            name='created_during_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comparacio',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
